---
- hosts: AnsibleHotspotTargets
  become: yes
  become_user: root
  vars:
    tunnel_name: "selfie-portal-working"
    tunnel_domain: "selfies.griffincreektrestle.net"
  roles:
    - role: cloudflare_tunnel 