---
- name: Include selfie app installation tasks
  include_tasks: install.yml
  tags:
    - selfie_app
    - install

- name: Include selfie app configuration tasks
  include_tasks: configure.yml
  tags:
    - selfie_app
    - configure

- name: Include selfie app service tasks
  include_tasks: service.yml
  tags:
    - selfie_app
    - service 