---

# Tested to work on Linux  6.12.25+rpt-rpi-v7 #1 SMP Raspbian 1:6.12.25-1+rpt1 (2025-04-30) armv7l GNU/Linux
# 8/13/2025




    - name: Run apt-get update & upgrade
      apt:
        upgrade: dist
        update_cache: yes 

    - name: Clone of 8812au-20210820.git drivers
      ansible.builtin.git:
        repo: https://github.com/morrownr/8812au-20210820.git
        dest: /home/pi/8812au_src
        force: yes
        accept_hostkey: yes
      register: git_clone_result
      retries: 3
      until: git_clone_result is succeeded
      tags:
       - AWUS036ACH
    
    - name: Set correct permissions on driver directory
      file:
        path: /home/pi/8812au_src
        state: directory
        owner: pi
        group: pi
        mode: '0755'
        recurse: yes
      become: true

#    - name: Change CONFIG_PLATFORM_I386_PC from y to n
##      ansible.builtin.replace:
#        path: /home/pi/8812au_src/Makefile
#        regexp: 'CONFIG_PLATFORM_I386_PC = y'
#        replace: 'CONFIG_PLATFORM_I386_PC = n'

 #   - name: Change CONFIG_PLATFORM_ARM_RPI from n to y
 #     ansible.builtin.replace:
#        path: /home/pi/8812au_src/Makefile
 #       regexp: 'CONFIG_PLATFORM_ARM_RPI = n'
 #       replace: 'CONFIG_PLATFORM_ARM_RPI = y'

    - name: Run install-driver.sh with automatic responses to prompts
      ansible.builtin.expect:
        command: sudo ./install-driver.sh
        chdir: /home/pi/8812au_src
        responses:
          'Do you want to edit the driver options file now\? \(recommended\) \[Y/n\]': 'n'
          'Do you want to apply the new options by rebooting now\? \(recommended\) \[Y/n\]': 'n'
        timeout: 1800
      become: true

# This causes the device to get orphaned and should be avoided.
#    - name: Restart NetworkManager
#      ansible.builtin.service:
#        name: NetworkManager
#        state: restarted
##      become: true

    - name: Show IP address information
      ansible.builtin.shell: ip a | cat
      become: true

    - name: Reboot the system
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30