   - name: Install ufw
     apt:
       name: ufw
       state: present
       update_cache: true

   - name: Block SSH on WiFi interface
     command: ufw deny in on {{ wifi_interface }}

   - name: Allow SSH on Ethernet interface
     command: ufw allow in on eth0 to any port 22

#   - name: Allow 80 & 443 on Wlan interface
#     command: ufw allow in on wlan0 to any port 80,443

   - name: Allow HTTP and HTTPS on Ethernet and wifi interface
     ufw:
       rule: allow
       src: any
       interface: "{{ item }}"
       direction: in
       port: 53,80,443,8000
       proto: tcp
       state: enabled
     loop:
       - eth0
       - {{ wifi_interface }}

   - name: Allow DNS
     ufw:
       rule: allow
       src: any
       interface: {{ wifi_interface }}
       direction: in
       port: '53'
       proto: udp
       state: enabled

# This should get inverted when builds are finally proven to work.  

   - name: Disable UFW
     command: ufw --force disable