---

# //todo: Rename this to hostapd_kill.yml and add a reference to in main.yml


   - name: Stop and disable hostapd service
     systemd:
       name: hostapd
       state: stopped
       enabled: no
     tags: hotspot
     ignore_errors: true

   - name: Mask hostapd service to prevent it from starting
     command: systemctl mask hostapd.service
     tags: hotspot
     ignore_errors: true

   - name: Remove hostapd configuration files
     file:
       path: "{{ item }}"
       state: absent
     loop:
       - /etc/hostapd/CaptivePortalAPD.conf
       - /etc/hostapd/hostapd.conf
       - /etc/default/hostapd
     tags: hotspot

   - name: Remove hostapd init.d script
     file:
       path: /etc/init.d/hostapd
       state: absent
     tags: hostapd

   # Keep dhcpcd configuration for static IP assignment
   - name: Configure dhcpcd.conf with the selected WiFi interface
     template:
       src: "{{ root_playbook_dir }}/templates/dhcpcd.conf.j2"
       dest: /etc/dhcpcd.conf
       owner: root
       group: netdev
       mode: 0664
     tags: 
     - os_config_files
     - streamer