---
     
    - name: Install Nginx package
      apt:
        name: nginx
        state: present

    - name: Update server_name in Nginx configuration
      replace:
        path: /etc/nginx/sites-available/default
        regexp: 'ansibledest\.local'
        replace: "{{ hostname }}"

    - name: Copy nginx configuration files over to target
      synchronize:
        src: "{{ root_playbook_dir }}/etc/nginx/"
        dest: /etc/nginx
        recursive: yes
     
