---
#https://snapcraft.io/docs/installing-snap-on-raspbian
#https://certbot.eff.org/instructions?ws=nginx&os=debianbuster      
    - name: Installing snapd
      apt:
        name: snapd
        state: present

    - name: Reboot the system
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30

    - name: Install core
      community.general.snap:
        name:
          - core

    - name: Update snap core
      command: snap refresh core

    - name: Install certbot
      community.general.snap:
        name: certbot
        classic: true

    - name: Ensure snakeoil SSL certificates are available
      package:
        name: ssl-cert
        state: present

    - name: Generate snakeoil certificates if missing
      command: make-ssl-cert generate-default-snakeoil --force-overwrite
      args:
        creates: /etc/ssl/certs/ssl-cert-snakeoil.pem

    - name: Generate private key (custom certificate)
      openssl_privatekey:
        path: /etc/ssl/private/nginx-selfsigned.key
        size: 2048

    - name: Generate self-signed certificate (custom certificate)  
      openssl_certificate:
        path: /etc/ssl/certs/nginx-selfsigned.crt
        privatekey_path: /etc/ssl/private/nginx-selfsigned.key
        provider: selfsigned
        selfsigned_not_after: "+365d"  # Valid for 365 days

    - name: Ensure nginx user can access SSL certificates
      file:
        path: "{{ item }}"
        group: ssl-cert
        mode: '0640'
      loop:
        - /etc/ssl/private/ssl-cert-snakeoil.key
        - /etc/ssl/private/nginx-selfsigned.key
      ignore_errors: true

    - name: Create directory for Nginx SSL files
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Generate Diffie-Hellman parameters
      openssl_dhparam:
        path: /etc/nginx/ssl/dhparams-thepub.local.pem
        size: 2048
        state: present
      notify: restart nginx
      timeout: 10000

    - name: Create symbolic link for certbot
      command:
        cmd: ln -s /snap/bin/certbot /usr/bin/certbot
