---

   - name: Create /var/www/html directory
     file: path=/var/www/html state=directory mode=0755 owner=www-data group=www-data
     tags: 
       - webserver
       - icecast
       - streamer

   - name: chmoding /var/www/html/
     file:
       path: /var/www/html/
       owner: www-data
       group: www-data
       mode: 0755
       recurse: yes
     tags: web

   - name: adding existing user pi to groups www-data
     user:
       name: pi
       groups: www-data
       append: yes
     tags: 
     - streamer
     - icecast
     - web

   - name: Copy www files over to target
     synchronize:
       src: "{{ root_playbook_dir }}/var/www/"
       dest: /var/www/
       recursive: yes
     tags: 
     - streamer
     - icecast
     - ices
  
   - name: Rename the lower tier Tokume website directory
     command: "mv /var/www/ansibledest.local/sites/ansibledest.local /var/www/ansibledest.local/sites/{{ hostname }}"

   - name: Rename the Tokumei website directory
     command: "mv /var/www/ansibledest.local /var/www/{{ hostname }}"

   - name: Create symbolic link for thepub
     command: ln -s /etc/nginx/sites-available/thepub.local /etc/nginx/sites-enabled/
