---
   - name: restart nginx
     systemd:
       name: nginx
       state: restarted
       enabled: yes

   - name: reload nginx
     systemd:
       name: nginx
       state: reloaded

   - name: restart dnsmasq
     systemd:
       name: dnsmasq
       state: restarted
       enabled: yes

   - name: reload NetworkManager
     systemd:
       name: NetworkManager
       state: reloaded

   - name: restart avahi-daemon
     systemd:
       name: avahi-daemon
       state: restarted
       enabled: yes

   - name: restart nodogsplash
     systemd:
       name: nodogsplash
       state: restarted
       enabled: yes