[main]
# Don't manage the WiFi interface we're using for the access point
unmanaged-devices=interface-name:{{ wifi_interface }}

# Enable dnsmasq integration
dns=dnsmasq

# Don't automatically connect to WiFi networks
no-auto-default=* 